#!/usr/bin/env bash

set -e

args=()

while getopts "p:ibB:" opt; do
    case "$opt" in
    p)
        args+=(--test-name-pattern "$OPTARG")
        ;;
    i)
        args+=(--inspect)
        ;;
    b)
        args+=(--inspect-brk)
        ;;
    B)
        args+=(--inspect-brk="$OPTARG")
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
    esac
done
shift "$((OPTIND - 1))"

exec node --import tsx --test "${args[@]}" "$@"
