#!/usr/bin/env bash

set -e
set -o pipefail

args=()

# IMPROVE: consider using https://github.com/MoLow/reporters

loader_args=(--import tsx)
test_args=(--test)
while getopts "Fop:ibB:ndt" opt; do
    case "$opt" in
    p)
        args+=(--test-name-pattern "$OPTARG")
        ;;
    i)
        args+=(--inspect)
        ;;
    b)
        args+=(--inspect-brk)
        ;;
    B)
        args+=(--inspect-brk="$OPTARG")
        ;;
    n)
        loader_args+=(--require ts-node/register)
        ;;
    d)
        export QCFG_TEST_LOG_LEVEL=DEBUG
        ;;
    t)
        export QCFG_TEST_USE_TEST_DIR=1
        ;;
    o)
        test_args+=(--test-only)
        ;;
    F)
        fail=1
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
    esac
done
shift "$((OPTIND - 1))"

if [[ -n "$fail" ]]; then
    if node "${loader_args[@]}" "${test_args[@]}" "${args[@]}" --test-reporter tap "$@" 2>&1 | grep '# pass' | grep -v 'pass 0'; then
        echo "Some tests unexpectedly passed"
        exit 1
    fi
else
    set -x
    exec node "${loader_args[@]}" "${test_args[@]}" "${args[@]}" "$@"
fi


