#!/usr/bin/env bash

set -e

args=()

loader_args=(--import tsx)
while getopts "p:ibB:ndt" opt; do
    case "$opt" in
    p)
        args+=(--test-name-pattern "$OPTARG")
        ;;
    i)
        args+=(--inspect)
        ;;
    b)
        args+=(--inspect-brk)
        ;;
    B)
        args+=(--inspect-brk="$OPTARG")
        ;;
    n)
        loader_args+=(--require ts-node/register)
        ;;
    d)
        export QCFG_TEST_LOG_LEVEL=DEBUG
        ;;
    t)
        export QCFG_TEST_USE_TEST_DIR=1
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
    esac
done
shift "$((OPTIND - 1))"

exec node "${loader_args[@]}" --test "${args[@]}" "$@"

